; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32-c3-devkitm-1]
platform = espressif32
board = esp32-c3-devkitm-1
monitor_speed = 115200
board_build.flash_mode = dio
build_flags =
  -DARDUINO_USB_MODE=1
  -DARDUINO_USB_CDC_ON_BOOT=1 ;; cHange based on need using usb or uart
framework = arduino

; [env:esp32_c3_luatos]
; platform = espressif32
; board = esp32-c3-devkitm-1  ; Change board ID to target the ESP32-C3
; framework = arduino
; monitor_speed = 115200
; ; If you were using a specific port for the DevKitC, remove or update it:
; ; upload_port = COMx